DROP TABLE IF EXISTS `SeatingChart`;
DROP TABLE IF EXISTS `Employee`;
CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO INT NOT NULL
);

CREATE TABLE Employee (
    EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);